version: '3'
services:
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb-smart
    restart: always
    volumes:
      - ./data/influxdb:/var/lib/influxdb
#      - ./conf/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      # The API for InfluxDB is served on port 8086
      - "7086:8086"
  # query influx using 
  # docker-compose exec influxdb influx
    environment:
      - INFLUXDB_DB=telegraf
#      - INFLUXDB_USER=telegraf
#      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=telegraf
      - INFLUXDB_ADMIN_PASSWORD=$INFLUXDB_PASSWORD
      - INFLUXDB_META_DIR=/var/lib/influxdb/meta2

  telegraf:
    image: telegraf:alpine
    container_name: telegraf-smart
    hostname: telle
    restart: always
    user: telegraf:998
#    privileged: true
    volumes:
      - ./conf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /:/hostfs:ro
      - /var/run/utmp:/var/run/utmp:ro
    environment:
      - HOST_MOUNT_PREFIX=/hostfs
      - HOST_PROC=/hostfs/proc    
    depends_on:
      - influxdb

  mqtt-broker:
    container_name: mqtt-broker-smart
    image: eclipse-mosquitto:2
    restart: always
    volumes:
      - ./conf/mqtt.conf:/mosquitto/config/mosquitto.conf
      - ./data/mosquitto:/mosquitto/data
      - ./conf/passwd:/mosquitto/passwd
      - ./conf/acl:/mosquitto/acl
    ports:
      - "1883:1883/tcp"
    healthcheck:
      test: "mosquitto_sub -t '$$SYS/#' -C 1 | grep -v Error || exit 1"
      interval: 45s
      timeout: 5s
      retries: 5

  public_grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana-smart
    restart: always
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./conf/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3030:3000
